server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

URIEncoding: UTF-8

logging:
  level:
    org:
      springframework:
        web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
        security: TRACE
        nodeValue: DEBUG
      hibernate: ERROR
