spring:
  application:
    name: sprout-seek

server:
  port: 8100

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8100/eureka

URIEncoding: UTF-8

logging:
  level:
    org:
      springframework:
        web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
        security: TRACE
        nodeValue: DEBUG
      hibernate: ERROR
