server:
  port: 8090

URIEncoding: UTF-8

logging:
  level:
    org:
      springframework:
        web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
        security: TRACE
        nodeValue: DEBUG
      hibernate: ERROR
