spring:
  application:
    name: dumb-service

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka

URIEncoding: UTF-8

logging:
  level:
    org:
      springframework:
        web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
        security: TRACE
        nodeValue: DEBUG
      hibernate: ERROR
