server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka

spring:
  application:
    name: sprout-route
  cloud:
    gateway:
      routes:
        - id: dumb-service
          uri: lb://dumb-service
          predicates:
            - Path=/dumb-service/{segment}
          filters:
            - StripPrefix=1
        - id: idiot-service
          uri: lb://idiot-service
          predicates:
            - Path=/idiot-service/{segment}
          filters:
            - StripPrefix=1
        - id: sprout-seek
          uri: http://localhost:8100
          predicates:
            - Path=/eureka/web/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: DEBUG
            nodeValue: TRACE
    root: DEBUG
